# NUMPY

NumPy stands for Numerical Python. It is a Python library used for working with an array. In Python, we use the list for the array but it’s slow to process. 

Consider a program that will create a list of squares of the numbers 0 to 4320, using the list and numpy library

In [1]:
import numpy as np
import timeit

t = timeit.Timer("[i**2 for i in range(4321)]")
t.timeit(number=1000) #
t = timeit.Timer("np.arange(4321)**2","import numpy as np")
t.timeit(number=1000)

0.004810462000023108

Types of Array:

1. One Dimensional Array
1. Multi-Dimensional Array

**Uni-Dimensional Array**

In [2]:
# importing numpy module
import numpy as np
# creating list
list = [1, 2, 3, 4]
# creating numpy array
sample_array = np.array(list)
print("List in python : ", list)
print("Numpy Array in python :", sample_array)

List in python :  [1, 2, 3, 4]
Numpy Array in python : [1 2 3 4]


**Multi-Dimensional Array**

In [3]:
# creating list 
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
# creating numpy array
sample_array = np.array([list_1,list_2,list_3])
print("Numpy multi dimensional array in Python\n", sample_array)

# print shape of the array
print("Shape of the array :",   sample_array.shape)

Numpy multi dimensional array in Python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of the array : (3, 4)


In general, NumPy arrays are a homogeneous kind of data structure that has the same types of items. The main benefit of an array is its certainty of storage size because of its same type of items. A Python list uses a loop to iterate the elements and perform operations on them. Another benefit of NumPy arrays is to offer vectorized operations instead of iterating each item and performing operations on it. NumPy arrays are indexed just like a Python list and start from 0.

In [4]:
a=np.array([(1,2,3),(4,5,6)])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
print(a.size)
print(len(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
6
2


**NumPy array numerical data types**

![](../images/pythontyp.jpg)

In [5]:
arr=np.arange(1,11, dtype= np.float32)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


It is also another way to create a NumPy array is with arange(). It creates an evenly spaced NumPy array. Three values – start, stop, and step – can be passed to the arange(start,stop[,step]) function. The start is the initial value of the range, the stop is the last value of the range, and the step is the increment in that range. The stop parameter is compulsory. 

The arange(1,11) function will return 1 to 10 values with one step because the step is, by default, 1. The arrange() function generates a value that is one less than the stop parameter value.

**Data type character codes**

Character codes are included for backward compatibility with Numeric. Numeric is the
predecessor of NumPy. Its use is not recommended, but the code is supplied here because
it pops up in various locations. You should use the dtype object instead.

![](../images/pythoncode.jpg)

In [6]:
var1=np.arange(1,11, dtype='f')
print(var1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


**Slicing NumPy arrays**

Indexing prefers to select a single value while slicing is used to select multiple values from an array. NumPy arrays also support negative indexing and slicing. Here, the negative sign indicates the opposite direction and indexing starts from the right-hand side with a starting value of -1.

In the slice operation, we use the colon symbol to select the collection of values. Slicing takes three values: start, stop, and step:

In [7]:
arr = np.arange(0,10)
print(arr)
print(arr[2])
print(arr[-2])
print(arr[3:])
print(arr[-3:])
print(arr[2:7:2])

[0 1 2 3 4 5 6 7 8 9]
2
8
[3 4 5 6 7 8 9]
[7 8 9]
[2 4 6]


**Boolean and fancy indexing**

Indexing techniques help us to select and filter elements from a NumPy array. Boolean indexing uses a Boolean expression in the place of indexes (in square brackets) to filter the NumPy array. This indexing returns elements that have a true value for the Boolean expression.

In [8]:
arr = np.arange(21,41,2)
print("Orignial Array:\n",arr)
# Boolean Indexing
print("After Boolean Condition:",arr[arr>30])

Orignial Array:
 [21 23 25 27 29 31 33 35 37 39]
After Boolean Condition: [31 33 35 37 39]


Fancy indexing is a special type of indexing in which elements of an array are selected by an array of indices. This means we pass the array of indices in brackets. Fancy indexing also supports multi-dimensional arrays. This will help us to easily select and modify a complex multi-dimensional set of arrays.

In [9]:
# Create NumPy Array
arr = np.arange(1,21).reshape(5,4)
print("Orignial Array:\n",arr)
# Selecting 2nd and 3rd row
indices = [1,2]
print("Selected 2nd and 3rd Row:\n", arr[indices])
# Selecting 3nd and 4th row
indices = [2,3]
print("Selected 3rd and 4th Row:\n", arr[indices])

Orignial Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Selected 2nd and 3rd Row:
 [[ 5  6  7  8]
 [ 9 10 11 12]]
Selected 3rd and 4th Row:
 [[ 9 10 11 12]
 [13 14 15 16]]


La función *where* devuelve una tupla de arrays. El primero indica las filas de los elementos que cumplen la condición, y el segundo las columnas.

La función *nonzero* equivale a *np.where(A!=0)*.

Las funciones *argmax* y *argmin* indican la posición del mayor y menor elemento, respectivamente.

In [10]:
A = np.random.permutation(np.r_[0:12]).reshape(3, 4)

print(A,"\n\n")

print(np.nonzero(A),"\n\n")

print(np.nonzero(A>5),"\n\n")

print(np.where(A>0),"\n\n")

print(np.where(A>5),"\n\n")

print(np.where(A==A.min()),"\n\n")

print(np.argmax(A),"\n\n")

A[0][0]=0

print(np.where(A==A.min()),"\n\n")

print(A,"\n\n")

print(np.argmin(A),"\n\n")

[[ 0  7  8  3]
 [ 5  2 11 10]
 [ 4  6  1  9]] 


(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])) 


(array([0, 0, 1, 1, 2, 2]), array([1, 2, 2, 3, 1, 3])) 


(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])) 


(array([0, 0, 1, 1, 2, 2]), array([1, 2, 2, 3, 1, 3])) 


(array([0]), array([0])) 


6 


(array([0]), array([0])) 


[[ 0  7  8  3]
 [ 5  2 11 10]
 [ 4  6  1  9]] 


0 


