# PANDAS

The Pandas library is designed to work with a panel or tabular data. Pandas is a fast, highly efficient, and productive tool for manipulating and analyzing string, numeric, datetime, and time-series data. pandas provides data structures such as DataFrames and Series. A pandas DataFrame is a tabular, two-dimensional labeled and indexed data structure with a grid of rows and columns. Its columns are heterogeneous types. It has the capability to work with different types of objects, carry out grouping and joining operations, handle missing values, create pivot tables, and deal with dates. 

In [1]:
import pandas as pd
import numpy as np

A=np.r_[:12].reshape(4,3)
print(A,"\n")

print(pd.DataFrame(A),"\n")
print(pd.DataFrame(A, columns=['A','B','C']),"\n")

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11 

   A   B   C
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11 



Let's create a DataFrame using a dictionary of the list:

In [2]:
data ={'Name': ['Kasia', 'Ola', 'Ela', 'Tomek'], 'Age': [23, 45,46, 52]}
df1 = pd.DataFrame(data) 
df1
df1.head()

Name  Age
0  Kasia   23
1    Ola   45
2    Ela   46
3  Tomek   52

# Task

Let us create a dataframe containing morphometric measurements of eight birds. The symbol NA stands for a missing value. The measured variables are the lengths of the wing (measured as the wing chord), leg (a standard measure of the tarsus), head (from the bill tip to the back of the skull), and weight.

In [3]:
values=np.array([59,22.3,31.2,9.5,55,19.7,30.4,13.8,53.5,20.8,30.6,14.8,55,20.3,30.3,15.2,52.5,20.8,30.3,15.5,57.5,21.5,30.8,15.6,53,20.6,32.5,15.6,55,21.5,np.nan,15.7]).reshape(8,4)
data=['Wingrd','Tarsus','Head','Wt']

A=pd.DataFrame(values,columns=data)
A

Wingrd  Tarsus  Head    Wt
0    59.0    22.3  31.2   9.5
1    55.0    19.7  30.4  13.8
2    53.5    20.8  30.6  14.8
3    55.0    20.3  30.3  15.2
4    52.5    20.8  30.3  15.5
5    57.5    21.5  30.8  15.6
6    53.0    20.6  32.5  15.6
7    55.0    21.5   NaN  15.7